export const mockEvents = [
  {
    id: "1",
    title: "Next.js 15 リリース記念！最新機能を学ぶ勉強会",
    description:
      "Next.js 15 がリリースされました。新機能の Turbopack や Partial Prerendering について詳しく解説します。",
    date: "2026-02-15",
    time: "19:00",
    location: "オンライン",
    capacity: 100,
    participants: 87,
    tags: ["Next.js", "React", "フロントエンド"],
    organizer: "Tokyo Web Developers",
  },
  {
    id: "2",
    title: "Rust で作る高速 Web API ハンズオン",
    description:
      "Rust と Axum を使って、高速で安全な Web API を構築する方法を実践的に学びます。",
    date: "2026-02-18",
    time: "14:00",
    location: "渋谷オフィス",
    capacity: 30,
    participants: 28,
    tags: ["Rust", "Axum", "バックエンド"],
    organizer: "Rust Tokyo",
  },
  {
    id: "3",
    title: "PostgreSQL パフォーマンスチューニング入門",
    description:
      "実践的なクエリ最適化とインデックス設計について、実例を交えながら解説します。",
    date: "2026-02-20",
    time: "19:30",
    location: "オンライン",
    capacity: 150,
    participants: 142,
    tags: ["PostgreSQL", "データベース", "パフォーマンス"],
    organizer: "DB Study Group",
  },
  {
    id: "4",
    title: "TypeScript 型パズル解説会",
    description:
      "TypeScript の高度な型システムを使った型パズルを一緒に解きながら、型の理解を深めます。",
    date: "2026-02-22",
    time: "13:00",
    location: "オンライン",
    capacity: 80,
    participants: 65,
    tags: ["TypeScript", "型システム"],
    organizer: "TS Lovers",
  },
  {
    id: "5",
    title: "GitHub Actions によるCI/CD実践",
    description:
      "GitHub Actions を使った自動テスト、デプロイ、リリースフローの構築方法を学びます。",
    date: "2026-02-25",
    time: "19:00",
    location: "新宿会議室",
    capacity: 40,
    participants: 35,
    tags: ["GitHub Actions", "CI/CD", "DevOps"],
    organizer: "DevOps Japan",
  },
  {
    id: "6",
    title: "Docker & Kubernetes ハンズオン",
    description:
      "コンテナ技術の基礎から実践まで。Kubernetes でのアプリケーションデプロイを体験します。",
    date: "2026-03-01",
    time: "10:00",
    location: "六本木オフィス",
    capacity: 25,
    participants: 22,
    tags: ["Docker", "Kubernetes", "コンテナ"],
    organizer: "Cloud Native Meetup",
  },
  {
    id: "7",
    title: "GraphQL スキーマ設計ベストプラクティス",
    description:
      "実務で役立つ GraphQL スキーマの設計パターンとアンチパターンを紹介します。",
    date: "2026-03-05",
    time: "19:30",
    location: "オンライン",
    capacity: 120,
    participants: 98,
    tags: ["GraphQL", "API設計"],
    organizer: "GraphQL Tokyo",
  },
  {
    id: "8",
    title: "Vue 3 Composition API 完全ガイド",
    description:
      "Vue 3 の Composition API を使った効率的なコンポーネント設計を学びます。",
    date: "2026-03-08",
    time: "14:00",
    location: "オンライン",
    capacity: 100,
    participants: 73,
    tags: ["Vue.js", "フロントエンド"],
    organizer: "Vue.js Japan",
  },
] as const;
